name: first-action
on: push
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: echo text
        run: echo "Job ran successfully"
      - name: optional steps
        run: echo "Branch is bug fix"
        if: ${{ startsWith(github.ref_name, 'bug') }}