name: image-changes
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - "**.yaml"

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: pull repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: setup git
        run: |
          git config --global user.email "actions@fcc.ca"
          git config --global user.name "github actions"
      - name: calculate diff
        run: |
          python image-delta.py