name: unit-tests
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: pull repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: echo text
        run: |
          pip install pytest
          pytest